# Laravel Docker Compose Configuration
# This file defines the multi-container environment for a Laravel application

services:
  # PHP Application Service
  # This contains the PHP runtime with any extensions needed for Laravel
  app:
    build:
      context: ./docker/php # Location of Dockerfile for PHP service
    volumes:
      - ./app:/var/www/html # Mount the application code into the container
    depends_on:
      - db # Ensure database starts before the app
    networks:
      - app-network # Connect to the application network

  # Nginx Web Server
  # Handles HTTP requests and forwards PHP requests to the app service
  webserver:
    image: nginx:latest # Using the official Nginx image
    ports:
      - "8000:80" # Map container port 80 to host port 8000
    volumes:
      - ./app:/var/www/html # Mount application code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # Custom Nginx configuration
    depends_on:
      - app # Ensure PHP service starts before Nginx
    networks:
      - app-network

  # MariaDB Database Service
  # Stores the application data
  db:
    image: mariadb:latest # Using the official MariaDB image
    restart: always # Automatically restart the container if it stops
    environment:
      # Database configuration
      MYSQL_ROOT_PASSWORD: rootpassword # Root password (consider using Docker secrets for production)
      MYSQL_DATABASE: laravel # Database name for application
      MYSQL_USER: laravel # Regular database user
      MYSQL_PASSWORD: laravelpassword # User password
    ports:
      - "3307:3306" # Map container port 3306 to host port 3307
        # NOTE: In Laravel's .env file, use DB_PORT=3306 (the internal port)
    volumes:
      - dbdata:/var/lib/mysql # Persist database data
    networks:
      - app-network

# Named volumes for persistent data
volumes:
  dbdata: # Volume for database files to persist between container restarts

# Custom networks
networks:
  app-network: # Network for all services to communicate with each other
