# Laravel Docker Compose Configuration
# This file defines the multi-container environment for a Laravel application

services:
  # PHP Application Service
  app:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    networks:
      - app-network

  # Nginx Web Server with ModSecurity
  webserver:
    image: owasp/modsecurity-crs:nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/custom-laravel.conf:/etc/nginx/conf.d/custom-laravel.conf
    depends_on:
      - app
    networks:
      - app-network

  # MariaDB Database Service
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
    ports:
      - "3330:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network

# Named volumes for persistent data
volumes:
  dbdata:

# Custom networks
networks:
  app-network:
